export default {
  account: {
    id: 'string',
    email: 'string',
    username: 'string',
    firstName: 'string',
    lastName: 'string',
    contactNumber: 'string',
    createdAt: 'date',
    role: 'role',
    parentAccountId: 'string',
  },
  role: {
    id: 'string',
    name: 'string',
    description: 'string',
    isDeveloper: 'boolean',
    isDeleted: 'boolean',
    updatedAt: 'date',
    createdAt: 'date',
    roleScope: 'roleScope',
    roleGroupId: 'string',
    roleGroup: 'roleGroup',
    level: 'string',
  },
  roleScope: {
    roleID: 'string',
    scopeID: 'string',
    scope: 'scope',
  },
  scope: {
    id: 'string',
    type: 'string',
    name: 'string',
    description: 'string',
  },
  roleGroup: {
    id: 'string',
    name: 'string',
    description: 'string',
    isDeleted: 'boolean',
  },
  client: {
    id: 'string',
    firstName: 'string',
    lastName: 'string',
    contactNumber: 'string',
    description: 'string',
    email: 'string',
    address: 'string',
    isDeleted: 'boolean',
    createdAt: 'date',
  },
  project: {
    id: 'string',
    name: 'string',
    description: 'string',
    budget: 'currency',
    address: 'string',
    isDeleted: 'boolean',
    startDate: 'date',
    endDate: 'date',
    status: 'enum',
    client: 'client',
    computedDate: 'string',
  },
  boardLane: {
    id: 'string',
    name: 'string',
    description: 'string',
    order: 'number',
  },

  warehouse: { 
    id: 'string',
    name: 'string',
    location: 'string',
    size: 'number',
    storageCapacity: 'number',
    forkliftSystem: 'string',
    rackingSystem: 'string',
    lighting: 'string',
    loadingDock: 'string',
    security: 'string',
    climateControl: 'string',
    accessibility: 'string',
    createdAt: 'date',
    updatedAt: 'date',
    isDeleted: 'boolean',
    createdBy: 'account',
    updatedBy: 'account'
  },
};
