export default [
  {
    id: 'PROJECTS_PAGE',
    type: 'PAGE',
    name: 'Projects Page',
    description: 'Projects Page',
    isDeleted: false,
  },
  {
    id: 'ASSETS_MANAGEMENT_PAGE',
    type: 'PAGE',
    name: 'Assets Management Page',
    description: 'Assets Management Page',
    isDeleted: false,
  },
  {
    id: 'MANPOWER_PAGE',
    type: 'PAGE',
    name: 'Manpower Page',
    description: 'Manpower Page',
    isDeleted: false,
  },
  {
    id: 'TREASURY_PAGE',
    type: 'PAGE',
    name: 'Treasury Page',
    description: 'Treasury Page',
    isDeleted: false,
  },
  {
    id: 'LEADS_PAGE',
    type: 'PAGE',
    name: 'Leads Page',
    description: 'Leads Page',
    isDeleted: false,
  },
  {
    id: 'SETTINGS_PAGE',
    type: 'PAGE',
    name: 'Settings Page',
    description: 'Settings Page',
    isDeleted: false,
  },
  {
    id: 'ROLES_FEATURE',
    type: 'FEATURE',
    name: 'Access Roles Feature',
    description: 'Access Roles Feature',
    parentID: 'SETTINGS_PAGE',
    isDeleted: false,
  },
  {
    id: 'SCOPE_FEATURE',
    type: 'FEATURE',
    name: 'Access Scope Feature',
    description: 'Access Scope Feature',
    parentID: 'SETTINGS_PAGE',
    isDeleted: false,
  },
  {
    id: 'USERS_FEATURE',
    type: 'FEATURE',
    name: 'Access Users Feature',
    description: 'Access Users Feature',
    parentID: 'SETTINGS_PAGE',
    isDeleted: false,
  },
  {
    id: 'ROLE_GROUP_FEATURES',
    type: 'FEATURE',
    name: 'Access Role Group Feature',
    description: 'Access Role Group Feature',
    parentID: 'SETTINGS_PAGE',
    isDeleted: false,
  },
  {
    id: 'VIEW_SCOPE',
    type: 'ACTION',
    name: 'View Scope',
    description: 'View Scope',
    parentID: 'SCOPE_FEATURE',
    isDeleted: false,
  },
  {
    id: 'CREATE_SCOPE',
    type: 'ACTION',
    name: 'Create Scope',
    description: 'Create Scope',
    parentID: 'SCOPE_FEATURE',
    isDeleted: false,
  },
  {
    id: 'UPDATE_SCOPE',
    type: 'ACTION',
    name: 'Update Scope',
    description: 'Update Scope',
    parentID: 'SCOPE_FEATURE',
    isDeleted: false,
  },
  {
    id: 'DELETE_SCOPE',
    type: 'ACTION',
    name: 'Delete Scope',
    description: 'Delete Scope',
    parentID: 'SCOPE_FEATURE',
    isDeleted: false,
  },
  {
    id: 'VIEW_ROLE',
    type: 'ACTION',
    name: 'View Role',
    description: 'View Role',
    parentID: 'ROLES_FEATURE',
    isDeleted: false,
  },
  {
    id: 'VIEW_ROLE_GROUP',
    type: 'ACTION',
    name: 'View Role Group',
    description: 'View Role Group',
    parentID: 'ROLE_GROUP_FEATURES',
    isDeleted: false,
  },
  {
    id: 'CREATE_ROLE',
    type: 'ACTION',
    name: 'Create Role',
    description: 'Create Role',
    parentID: 'ROLES_FEATURE',
    isDeleted: false,
  },
  {
    id: 'CREATE_ROLE_GROUP',
    type: 'ACTION',
    name: 'Create Role Group',
    description: 'Create Role Group',
    parentID: 'ROLE_GROUP_FEATURES',
    isDeleted: false,
  },
  {
    id: 'UPDATE_ROLE',
    type: 'ACTION',
    name: 'Update Role',
    description: 'Update Role',
    parentID: 'ROLES_FEATURE',
    isDeleted: false,
  },
  {
    id: 'UPDATE_ROLE_GROUP',
    type: 'ACTION',
    name: 'Update Role Group',
    description: 'Update Role Group',
    parentID: 'ROLE_GROUP_FEATURES',
    isDeleted: false,
  },
  {
    id: 'DELETE_ROLE',
    type: 'ACTION',
    name: 'Delete Role',
    description: 'Delete Role',
    parentID: 'ROLES_FEATURE',
    isDeleted: false,
  },
  {
    id: 'DELETE_ROLE_GROUP',
    type: 'ACTION',
    name: 'Delete Role Group',
    description: 'Delete Role Group',
    parentID: 'ROLE_GROUP_FEATURES',
    isDeleted: false,
  },
  {
    id: 'VIEW_USERS',
    type: 'ACTION',
    name: 'View User',
    description: 'View User',
    parentID: 'USERS_FEATURE',
    isDeleted: false,
  },
  {
    id: 'CREATE_USERS',
    type: 'ACTION',
    name: 'Create User',
    description: 'Create User',
    parentID: 'USERS_FEATURE',
    isDeleted: false,
  },
  {
    id: 'UPDATE_USERS',
    type: 'ACTION',
    name: 'Update User',
    description: 'Update User',
    parentID: 'USERS_FEATURE',
    isDeleted: false,
  },
  {
    id: 'DELETE_USERS',
    type: 'ACTION',
    name: 'Delete User',
    description: 'Delete User',
    parentID: 'USERS_FEATURE',
    isDeleted: false,
  },
  {
    id: 'PROJECT_FEATURE',
    type: 'FEATURE',
    name: 'Access Project Feature',
    description: 'Access Project Feature',
    parentID: 'PROJECTS_PAGE',
    isDeleted: false,
  },
  {
    id: 'VIEW_PROJECT_TABLE',
    type: 'ACTION',
    name: 'View Project Table',
    description: 'View Project Table',
    parentID: 'PROJECT_FEATURE',
    isDeleted: false,
  },
  {
    id: 'VIEW_PROJECT_INFORMATION',
    type: 'ACTION',
    name: 'View Project Information',
    description: 'View Project Information',
    parentID: 'PROJECT_FEATURE',
    isDeleted: false,
  },
  {
    id: 'CREATE_PROJECT',
    type: 'ACTION',
    name: 'Create Project Information',
    description: 'Create Project Information',
    parentID: 'PROJECT_FEATURE',
    isDeleted: false,
  },
  {
    id: 'UPDATE_PROJECT',
    type: 'ACTION',
    name: 'Update Project Information',
    description: 'Update Project Information',
    parentID: 'PROJECT_FEATURE',
    isDeleted: false,
  },
  {
    id: 'DELETE_PROJECT',
    type: 'ACTION',
    name: 'Delete Project Information',
    description: 'Delete Project Information',
    parentID: 'PROJECT_FEATURE',
    isDeleted: false,
  },
  {
    id: 'BOARD_LANE_FEATURE',
    type: 'FEATURE',
    name: 'Access Board Lane Feature',
    description: 'Access Board Lane Feature',
    isDeleted: false,
  },
  {
    id: 'VIEW_BOARD_LANE_TABLE',
    type: 'ACTION',
    name: 'View Board Lane Table',
    description: 'View Board Lane Table',
    parentID: 'BOARD_LANE_FEATURE',
    isDeleted: false,
  },
  {
    id: 'VIEW_BOARD_LANE_INFORMATION',
    type: 'ACTION',
    name: 'View Board Lane Information',
    description: 'View Board Lane Information',
    parentID: 'BOARD_LANE_FEATURE',
    isDeleted: false,
  },
  {
    id: 'CREATE_BOARD_LANE',
    type: 'ACTION',
    name: 'Create Board Lane Information',
    description: 'Create Board Lane Information',
    parentID: 'BOARD_LANE_FEATURE',
    isDeleted: false,
  },
  {
    id: 'UPDATE_BOARD_LANE',
    type: 'ACTION',
    name: 'Update Board Lane Information',
    description: 'Update Board Lane Information',
    parentID: 'BOARD_LANE_FEATURE',
    isDeleted: false,
  },
  {
    id: 'DELETE_BOARD_LANE',
    type: 'ACTION',
    name: 'Delete Board Lane Information',
    description: 'Delete Board Lane Information',
    parentID: 'BOARD_LANE_FEATURE',
    isDeleted: false,
  },
];
