export default {
  role: {
    name: 'Role List',
    prismaKey: 'role',
    responseRef: 'role',
    defaultOrderBy: 'createdAt',
    sort: [{ key: 'name', label: 'Role Name', column: 'name' }],
    filter: [{ key: 'deleted', label: 'Role Deleted', column: 'isDeleted' }],
    search: [{ key: 'name', label: 'Role Name', column: 'name' }],
  },
  account: {
    name: 'Account List',
    prismaKey: 'account',
    responseRef: 'account',
    defaultOrderBy: 'createdAt',
    sort: [{ key: 'name', label: 'Role Name', column: 'name' }],
    filter: [{ key: 'deleted', label: 'Account Deleted', column: 'isDeleted' }],
    search: [{ key: 'name', label: 'Role Name', column: 'name' }],
  },
  roleGroup: {
    name: 'Role Group List',
    prismaKey: 'roleGroup',
    responseRef: 'roleGroup',
    defaultOrderBy: 'createdAt',
    sort: [{ key: 'name', label: 'Role Name', column: 'name' }],
    filter: [{ key: 'deleted', label: 'Role Deleted', column: 'isDeleted' }],
    search: [{ key: 'name', label: 'Role Name', column: 'name' }],
  },
  scope: {
    name: 'Scope List',
    prismaKey: 'scope',
    responseRef: 'scope',
    defaultOrderBy: 'id',
    sort: [{ key: 'name', label: 'Scope Name', column: 'name' }],
    filter: [{ key: 'deleted', label: 'Scope Deleted', column: 'isDeleted' }],
    search: [{ key: 'name', label: 'Scope Name', column: 'name' }],
  },
  project: {
    name: 'Project List',
    prismaKey: 'project',
    responseRef: 'project',
    defaultOrderBy: 'startDate',
    sort: [{ key: 'name', label: 'Project Name', column: 'name' }],
    filter: [{ key: 'deleted', label: 'Project Deleted', column: 'isDeleted' }],
    search: [{ key: 'name', label: 'Project Name', column: 'name' }],
  },
  boardLane: {
    name: 'Board Lane List',
    prismaKey: 'boardLane',
    responseRef: 'boardLane',
    defaultOrderBy: 'createdAt',
    sort: [{ key: 'name', label: 'Board Lane Name', column: 'name' }],
    filter: [
      { key: 'deleted', label: 'Board Lane Deleted', column: 'isDeleted' },
    ],
    search: [{ key: 'name', label: 'Board Lane Name', column: 'name' }],
  },
};
